# Generated by Django 3.2.7 on 2021-10-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_space', models.DecimalField(decimal_places=0, max_digits=10)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
