# Generated by Django 3.2.7 on 2021-10-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=20)),
                ('reserved', models.DecimalField(decimal_places=0, max_digits=3)),
                ('less_than_1hr', models.BooleanField(default=False)),
                ('more_than_1hr', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
