# Generated by Django 3.2.7 on 2021-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('company_name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=True)),
            ],
        ),
    ]
