# Generated by Django 3.2.7 on 2021-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
