# Generated by Django 3.2.7 on 2021-10-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
